# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml_monitor.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ml_monitor.proto\"\x1e\n\rStatusRequest\x12\r\n\x05token\x18\x01 \x01(\t\" \n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\">\n\x11\x44\x61taUploadRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x1a\n\x05\x66iles\x18\x02 \x03(\x0b\x32\x0b.FileUpload\"/\n\nFileUpload\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"&\n\x12\x44\x61taUploadResponse\x12\x10\n\x08messages\x18\x01 \x03(\t\"1\n\x10InferenceRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\"#\n\x11InferenceResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\xa4\x01\n\tMLService\x12,\n\tGetStatus\x12\x0e.StatusRequest\x1a\x0f.StatusResponse\x12\x35\n\nUploadData\x12\x12.DataUploadRequest\x1a\x13.DataUploadResponse\x12\x32\n\tInference\x12\x11.InferenceRequest\x1a\x12.InferenceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_monitor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STATUSREQUEST']._serialized_start=20
  _globals['_STATUSREQUEST']._serialized_end=50
  _globals['_STATUSRESPONSE']._serialized_start=52
  _globals['_STATUSRESPONSE']._serialized_end=84
  _globals['_DATAUPLOADREQUEST']._serialized_start=86
  _globals['_DATAUPLOADREQUEST']._serialized_end=148
  _globals['_FILEUPLOAD']._serialized_start=150
  _globals['_FILEUPLOAD']._serialized_end=197
  _globals['_DATAUPLOADRESPONSE']._serialized_start=199
  _globals['_DATAUPLOADRESPONSE']._serialized_end=237
  _globals['_INFERENCEREQUEST']._serialized_start=239
  _globals['_INFERENCEREQUEST']._serialized_end=288
  _globals['_INFERENCERESPONSE']._serialized_start=290
  _globals['_INFERENCERESPONSE']._serialized_end=325
  _globals['_MLSERVICE']._serialized_start=328
  _globals['_MLSERVICE']._serialized_end=492
# @@protoc_insertion_point(module_scope)
